apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: UABBADUANQB3ADAAcgBkAEAAMQA=
  username: cgBvAG8AdAA=
  rootpassword: UABBADUANQB3ADAAcgBkAEAAMQA=
  MYSQL_ROOT_PASSWORD: UABBADUANQB3ADAAcgBkAEAAMQA=
  
