apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - protocol: 'TCP'
    port: 3000
    targetPort: 3000
  - protocol: 'TCP'
    port: 8080
    targetPort: 8080
  - protocol: 'TCP' 
    port: 3306
    targetPort: 3306 
  - protocol: 'TCP'  
    port: 8082
    targetPort: 80
