apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-depl
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: feapp
        image: finominom/myvueclient:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      - name: beapp
        image: finominom/jaciserver  
                      
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      - name: mysqldb
        image: mysql:8.0.26
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: MYSQL_USER
            
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: jaci-config
              key: MYSQL_DATABASE      
            

        resources:
          limits:
            memory: "1000Mi"   
            cpu: "1000m"
        ports:
        - containerPort: 3306 
        volumeMounts:
          - name: mysqlsecvol
            mountPath: /var/lib/mysql/secret
          - name: mysqlcfgvol
            mountPath: /var/lib/mysql/config
      
      - name: phpmyadmin
        image: phpmyadmin:latest
        env:
          - name: PMA_HOST
            valueFrom:
              configMapKeyRef:
                name: jaci-config
                key: PMA_HOST
          - name: PMA_ARBITRARY
            valueFrom:
              configMapKeyRef:
                name: jaci-config
                key: PMA_ARBITRARY
          - name: PMA_PORT      
            valueFrom:
              configMapKeyRef:
                name: jaci-config
                key: PMA_PORT        
              
        resources:
          limits:
            memory: "1008Mi" 
            cpu: "1000m"  
        ports:
        - containerPort: 80  
        volumeMounts:
          - name: pmacfgvol   
            mountPath: /var/www/phpmyadmin/config  
          - name: secretvol
            mountPath: /var/www/phpmyadmin/secret  
      volumes:
        - name: secretvol
          secret:
            secretName: mysecret
        - name: pmacfgvol
          configMap:
            name: jaci-config     
        - name: mysqlsecvol
          secret:
            secretName: mysecret
        - name: mysqlcfgvol  
          configMap:
            name: jaci-config              

          
