apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypv
  labels: 
    app: myapp
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  
