apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: mysql:latest
    resources:
      limits:
        memory: "500Mi"
        cpu: "1000m"
    ports:
      - containerPort: 3306
    imagePullPolicy: Never
    


