apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      tier: mysql
  strategy:
    type: Recreate    
  template:
    metadata:
      labels:
        app: myapp
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        resources:
          requests:
            memory: "250Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "1000m"

        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
        ports:
        - containerPort: 3306
          name: mysql-port
          protocol: TCP
        volumeMounts:
          - name: mysqlpesvol
            mountPath: /var/lib/msql 
      volumes:
        - name: mysqlpesvol
          persistentVolumeClaim:
            claimName: mypvc 
